name: yp11-pyspark-training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - ipykernel=6.12.1
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.5.1
  - matplotlib-inline=0.1.3
  - notebook=6.4.10
  - nb_conda_kernels  
  - openjdk=8.0.332
  - pip=22.0.4
  - pip:
    - matplotlib==3.3.4
    - numpy==1.20.1
    - pandas==1.2.4
    - patsy==0.5.2
    - pyspark==3.0.2
